-- 编号: 015, 描述: 客户拜访记录表, 创建人: 阿坚, 日期: 2026-07-06

-- P1-08: 客户拜访记录表
-- 用于记录销售人员拜访客户的详细信息

CREATE TABLE IF NOT EXISTS t_customer_visit (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '拜访记录ID',
  visit_no VARCHAR(64) NOT NULL COMMENT '拜访单号',
  customer_id BIGINT UNSIGNED NOT NULL COMMENT '客户ID',
  customer_name VARCHAR(64) NOT NULL COMMENT '客户名称快照',
  customer_mobile VARCHAR(20) DEFAULT NULL COMMENT '客户手机号',
  store_id BIGINT UNSIGNED NOT NULL COMMENT '所属门店ID',
  visitor_id BIGINT UNSIGNED NOT NULL COMMENT '拜访人(员工ID)',
  visitor_name VARCHAR(64) NOT NULL COMMENT '拜访人姓名',
  visit_type VARCHAR(32) NOT NULL DEFAULT 'ONSITE' COMMENT '拜访类型：ONSITE(现场拜访)/PHONE(电话拜访)/ONLINE(线上拜访)',
  visit_purpose VARCHAR(32) NOT NULL DEFAULT 'ROUTINE' COMMENT '拜访目的：ROUTINE(常规拜访)/ORDER(下单)/COLLECTION(催收)/COMPLAINT(投诉处理)/PROMOTION(推广)/AFTER_SALE(售后)',
  visit_date DATE NOT NULL COMMENT '拜访日期',
  start_time DATETIME DEFAULT NULL COMMENT '拜访开始时间',
  end_time DATETIME DEFAULT NULL COMMENT '拜访结束时间',
  duration_minutes INT DEFAULT NULL COMMENT '拜访时长(分钟)',
  address VARCHAR(255) DEFAULT NULL COMMENT '拜访地址',
  latitude DECIMAL(10, 7) DEFAULT NULL COMMENT '纬度',
  longitude DECIMAL(10, 7) DEFAULT NULL COMMENT '经度',
  contact_person VARCHAR(64) DEFAULT NULL COMMENT '联系人',
  contact_position VARCHAR(64) DEFAULT NULL COMMENT '联系人职位',
  contact_mobile VARCHAR(20) DEFAULT NULL COMMENT '联系人电话',
  visit_summary TEXT COMMENT '拜访总结',
  follow_up_required TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否需要跟进：0否 1是',
  follow_up_date DATE DEFAULT NULL COMMENT '下次跟进日期',
  follow_up_content VARCHAR(255) DEFAULT NULL COMMENT '跟进内容说明',
  next_action VARCHAR(255) DEFAULT NULL COMMENT '下一步行动计划',
  status VARCHAR(32) NOT NULL DEFAULT 'PLANNED' COMMENT '状态：PLANNED(计划中)/VISITED(已拜访)/COMPLETED(已完成)/CANCELLED(已取消)',
  related_order_no VARCHAR(64) DEFAULT NULL COMMENT '关联订单号',
  images JSON DEFAULT NULL COMMENT '拜访照片(JSON数组)',
  remark VARCHAR(255) DEFAULT NULL COMMENT '备注',
  tenant_id VARCHAR(36) NOT NULL DEFAULT 'default' COMMENT '租户ID',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_customer_visit_no (visit_no),
  KEY idx_customer_visit_customer (customer_id),
  KEY idx_customer_visit_visitor (visitor_id),
  KEY idx_customer_visit_date (visit_date),
  KEY idx_customer_visit_status (status),
  KEY idx_customer_visit_tenant (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='客户拜访记录表';
