-- 编号: 055, 描述: 添加积分商城商品表, 创建人: 阿坚, 日期: 2026-07-05
CREATE TABLE IF NOT EXISTS points_mall_item (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(128) NOT NULL COMMENT '商品名称',
  image VARCHAR(255) DEFAULT NULL COMMENT '商品图片',
  points INT NOT NULL COMMENT '所需积分',
  stock INT NOT NULL DEFAULT 0 COMMENT '库存',
  limit_per_user INT NOT NULL DEFAULT 1 COMMENT '每人限兑',
  valid_start DATE DEFAULT NULL COMMENT '有效期开始',
  valid_end DATE DEFAULT NULL COMMENT '有效期结束',
  status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态：ACTIVE/INACTIVE',
  sort_order INT NOT NULL DEFAULT 0 COMMENT '排序',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_status (status),
  INDEX idx_sort (sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='积分商城商品表';