-- 编号: 056, 描述: 添加积分商城订单表, 创建人: 阿坚, 日期: 2026-07-05
CREATE TABLE IF NOT EXISTS points_mall_order (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  order_no VARCHAR(64) NOT NULL COMMENT '订单号',
  user_id BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
  item_id BIGINT UNSIGNED NOT NULL COMMENT '商品ID',
  item_name VARCHAR(128) NOT NULL COMMENT '商品名称',
  points INT NOT NULL COMMENT '消耗积分',
  quantity INT NOT NULL DEFAULT 1 COMMENT '兑换数量',
  receiver_name VARCHAR(64) DEFAULT NULL COMMENT '收货人',
  receiver_mobile VARCHAR(20) DEFAULT NULL COMMENT '收货电话',
  receiver_address VARCHAR(255) DEFAULT NULL COMMENT '收货地址',
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT '状态：PENDING/DELIVERED/CANCELLED',
  delivered_at DATETIME DEFAULT NULL COMMENT '发货时间',
  cancelled_at DATETIME DEFAULT NULL COMMENT '取消时间',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_order_no (order_no),
  INDEX idx_user (user_id),
  INDEX idx_status (status),
  INDEX idx_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='积分商城订单表';