CREATE TABLE IF NOT EXISTS marketing_asset (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(128) NOT NULL COMMENT '素材名称',
  type VARCHAR(32) NOT NULL COMMENT '类型：IMAGE/VIDEO/COPYWRITING',
  url VARCHAR(500) DEFAULT NULL COMMENT '素材URL',
  thumbnail_url VARCHAR(500) DEFAULT NULL COMMENT '缩略图URL',
  content TEXT DEFAULT NULL COMMENT '文案内容',
  category VARCHAR(64) DEFAULT NULL COMMENT '分类',
  tags JSON DEFAULT NULL COMMENT '标签',
  file_size BIGINT DEFAULT NULL COMMENT '文件大小(字节)',
  status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态：ACTIVE/INACTIVE',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_type (type),
  INDEX idx_category (category),
  INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='营销素材表';