-- 编号: 061, 描述: 添加自定义报表计划表, 创建人: 阿坚, 日期: 2026-07-05
CREATE TABLE IF NOT EXISTS custom_report_schedule (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  template_id BIGINT UNSIGNED NOT NULL COMMENT '模板ID',
  name VARCHAR(128) NOT NULL COMMENT '任务名称',
  cron_expression VARCHAR(64) NOT NULL COMMENT '定时表达式',
  export_format VARCHAR(16) DEFAULT 'EXCEL' COMMENT '导出格式：EXCEL/PDF',
  recipients JSON DEFAULT NULL COMMENT '接收人列表',
  last_run_at DATETIME DEFAULT NULL COMMENT '上次执行时间',
  status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态：ACTIVE/PAUSED',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_template (template_id),
  INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='定时报表导出表';