CREATE TABLE IF NOT EXISTS verification_code (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  mobile VARCHAR(20) NOT NULL COMMENT '手机号',
  code VARCHAR(10) NOT NULL COMMENT '验证码',
  type VARCHAR(32) NOT NULL COMMENT '类型：LOGIN/BIND_PHONE/RESET_PASSWORD',
  expires_at DATETIME NOT NULL COMMENT '过期时间',
  used TINYINT NOT NULL DEFAULT 0 COMMENT '是否已使用',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_mobile_type (mobile, type),
  INDEX idx_expires (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='验证码表';