-- 编号: 064, 描述: 添加推送配置表, 创建人: 阿坚, 日期: 2026-07-05
CREATE TABLE IF NOT EXISTS t_push_config (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
  push_type VARCHAR(32) NOT NULL COMMENT '推送类型：ORDER/COLLECTION/MARKETING/SYSTEM',
  enabled TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用',
  quiet_start TIME DEFAULT NULL COMMENT '免打扰开始',
  quiet_end TIME DEFAULT NULL COMMENT '免打扰结束',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_user_type (user_id, push_type),
  INDEX idx_user (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='推送配置表';