CREATE TABLE IF NOT EXISTS push_template (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(64) NOT NULL COMMENT '模板编码',
  name VARCHAR(128) NOT NULL COMMENT '模板名称',
  push_type VARCHAR(32) NOT NULL COMMENT '推送类型：ORDER/COLLECTION/MARKETING/SYSTEM',
  channel VARCHAR(32) NOT NULL COMMENT '渠道：WECHAT_MP/SMS/APP_PUSH',
  title_template VARCHAR(255) NOT NULL COMMENT '标题模板',
  content_template TEXT NOT NULL COMMENT '内容模板',
  wechat_template_id VARCHAR(128) DEFAULT NULL COMMENT '微信模板ID',
  status TINYINT NOT NULL DEFAULT 1 COMMENT '状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_code (code),
  INDEX idx_type (push_type),
  INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='推送模板表';