-- 编号: 070, 描述: 品牌表, 创建人: 阿坚, 日期: 2026-07-05
-- 日期：2026-06-28

CREATE TABLE IF NOT EXISTS t_brand (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(64) NOT NULL COMMENT '品牌名称',
  logo VARCHAR(512) DEFAULT NULL COMMENT '品牌Logo',
  description VARCHAR(255) DEFAULT NULL COMMENT '品牌描述',
  sort_no INT NOT NULL DEFAULT 0 COMMENT '排序',
  status TINYINT NOT NULL DEFAULT 1 COMMENT '1启用 0停用',
  tenant_id VARCHAR(64) NOT NULL DEFAULT 'default' COMMENT '租户ID',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_brand_tenant (tenant_id),
  INDEX idx_brand_sort (sort_no)
) COMMENT='品牌表';