-- 单位表（Phase 2）
-- 日期：2026-06-28

CREATE TABLE IF NOT EXISTS unit (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(32) NOT NULL COMMENT '单位名称（瓶/箱/件/桶）',
  code VARCHAR(32) NOT NULL COMMENT '单位编码',
  type VARCHAR(16) NOT NULL DEFAULT 'BASE' COMMENT 'BASE基础单位/BOX组合单位',
  sort_no INT NOT NULL DEFAULT 0 COMMENT '排序',
  status TINYINT NOT NULL DEFAULT 1 COMMENT '1启用 0停用',
  tenant_id VARCHAR(36) NOT NULL DEFAULT 'default' COMMENT '租户ID',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_unit_tenant (tenant_id),
  INDEX idx_unit_sort (sort_no)
) COMMENT='单位表';