-- 商品中心字段补齐（Phase 2）
-- 日期：2026-06-28
-- 说明：补齐 product_spu / product_sku / product_category 缺失字段
-- 注意：ADD COLUMN IF NOT EXISTS 为 MariaDB 语法，MySQL 8.0 请使用
--       add_tenant_id.sql 中的 add_column_if_not_exists 存储过程替代

ALTER TABLE product_spu
  ADD COLUMN IF NOT EXISTS brand VARCHAR(128) DEFAULT NULL COMMENT '品牌',
  ADD COLUMN IF NOT EXISTS unit VARCHAR(32) DEFAULT NULL COMMENT '单位',
  ADD COLUMN IF NOT EXISTS specs VARCHAR(256) DEFAULT NULL COMMENT '规格',
  ADD COLUMN IF NOT EXISTS sort_no INT NOT NULL DEFAULT 0 COMMENT '排序',
  ADD COLUMN IF NOT EXISTS is_new TINYINT NOT NULL DEFAULT 0 COMMENT '新品标记',
  ADD COLUMN IF NOT EXISTS is_recommend TINYINT NOT NULL DEFAULT 0 COMMENT '推荐标记',
  ADD COLUMN IF NOT EXISTS description VARCHAR(512) DEFAULT NULL COMMENT '商品简介';

ALTER TABLE product_sku
  ADD COLUMN IF NOT EXISTS volume VARCHAR(32) DEFAULT NULL COMMENT '净含量（500ml/1L）',
  ADD COLUMN IF NOT EXISTS packaging VARCHAR(32) DEFAULT NULL COMMENT '包装类型（瓶装/罐装/桶装）';

ALTER TABLE product_category
  ADD COLUMN IF NOT EXISTS icon VARCHAR(256) DEFAULT NULL COMMENT '分类图标',
  ADD COLUMN IF NOT EXISTS code VARCHAR(64) DEFAULT NULL COMMENT '分类编码';