import "dotenv/config";

export const env = {
  PORT: Number(process.env.PORT || 8080),
  NODE_ENV: process.env.NODE_ENV || "production",
  JWT_SECRET: process.env.JWT_SECRET || "please-change-me",
  DB_HOST: process.env.DB_HOST || "127.0.0.1",
  DB_PORT: Number(process.env.DB_PORT || 3306),
  DB_USER: process.env.DB_USER || "zhixiang_app",
  DB_PASSWORD: process.env.DB_PASSWORD || "",
  DB_NAME: process.env.DB_NAME || "liquor_inventory",
  USE_MOCK_DB: process.env.USE_MOCK_DB === "true",
  REDIS_HOST: process.env.REDIS_HOST || "127.0.0.1",
  REDIS_PORT: Number(process.env.REDIS_PORT || 6379),
  DOMAIN: process.env.DOMAIN || "onepan.cn",
  API_DOMAIN: process.env.API_DOMAIN || "api.onepan.cn",
  ADMIN_DOMAIN: process.env.ADMIN_DOMAIN || "admin.onepan.cn",
  MERCHANT_DOMAIN: process.env.MERCHANT_DOMAIN || "m.onepan.cn",
  STORE_DOMAIN: process.env.STORE_DOMAIN || "store.onepan.cn",
  WECHAT_APP_ID: process.env.WECHAT_APP_ID || "",
  WECHAT_APP_SECRET: process.env.WECHAT_APP_SECRET || "",
  WECHAT_MCH_ID: process.env.WECHAT_MCH_ID || "",
  WECHAT_PAY_SERIAL_NO: process.env.WECHAT_PAY_SERIAL_NO || "",
  WECHAT_PAY_PRIVATE_KEY_PATH: process.env.WECHAT_PAY_PRIVATE_KEY_PATH || "",
  WECHAT_PAY_API_V3_KEY: process.env.WECHAT_PAY_API_V3_KEY || "",
  WECHAT_PAY_NOTIFY_URL: process.env.WECHAT_PAY_NOTIFY_URL || "",
  WX_APPID: process.env.WX_APPID || process.env.WECHAT_APP_ID || "",
  WX_APP_SECRET: process.env.WX_APP_SECRET || process.env.WECHAT_APP_SECRET || "",
  WX_MCH_ID: process.env.WX_MCH_ID || process.env.WECHAT_MCH_ID || "",
  WX_API_KEY: process.env.WX_API_KEY || process.env.WECHAT_PAY_API_V3_KEY || "",
};
