-- 缺列补建 SQL（2026-08-07T15:29:56.866Z）
SET NAMES utf8mb4;
ALTER TABLE t_purchase_payment ADD COLUMN approved_at DATETIME DEFAULT NULL;
ALTER TABLE t_purchase_payment ADD COLUMN approved_by BIGINT DEFAULT NULL;
ALTER TABLE t_purchase_payment ADD COLUMN paid_at DATETIME DEFAULT NULL;
ALTER TABLE t_purchase_payment ADD COLUMN paid_by BIGINT DEFAULT NULL;
ALTER TABLE t_retail_banner ADD COLUMN `store_id` BIGINT DEFAULT NULL COMMENT '门店ID';
ALTER TABLE t_retail_order ADD COLUMN cancelled_at DATETIME COMMENT '取消时间';
ALTER TABLE t_retail_order ADD COLUMN completed_at DATETIME COMMENT '完成时间';
ALTER TABLE t_retail_order ADD COLUMN delivery_time DATETIME COMMENT '配送时间';
ALTER TABLE t_retail_order ADD COLUMN user_phone VARCHAR(20) COMMENT '用户电话';
ALTER TABLE t_retail_order_item ADD COLUMN `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE t_retail_order_item ADD COLUMN `tenant_id` VARCHAR(32) NOT NULL COMMENT '租户ID';
ALTER TABLE t_retail_shop_config ADD COLUMN free_delivery_amount DECIMAL(10,2) COMMENT '免配送费金额';
ALTER TABLE t_sale_bill ADD COLUMN last_payment_time DATETIME DEFAULT NULL COMMENT '最近收款时间';
ALTER TABLE t_sale_bill ADD COLUMN last_share_time DATETIME DEFAULT NULL COMMENT '最近分享时间';
ALTER TABLE t_sale_bill ADD COLUMN locked_amount_flag TINYINT NOT NULL DEFAULT 0 COMMENT '金额是否锁定';
ALTER TABLE t_sale_bill ADD COLUMN share_collection_count INT NOT NULL DEFAULT 0 COMMENT '分享收款次数';
ALTER TABLE t_tenant ADD COLUMN address VARCHAR(255) COMMENT '详细地址';
ALTER TABLE t_tenant ADD COLUMN business_license VARCHAR(128) COMMENT '营业执照号';
ALTER TABLE t_tenant ADD COLUMN city VARCHAR(64) COMMENT '城市';
ALTER TABLE t_tenant ADD COLUMN company_scale VARCHAR(32) COMMENT '公司规模（如：1-10人、11-50人等）';
ALTER TABLE t_tenant ADD COLUMN contact_email VARCHAR(128) COMMENT '联系邮箱';
ALTER TABLE t_tenant ADD COLUMN contact_mobile VARCHAR(20) NOT NULL COMMENT '联系电话';
ALTER TABLE t_tenant ADD COLUMN contact_person VARCHAR(64) NOT NULL COMMENT '联系人';
ALTER TABLE t_tenant ADD COLUMN district VARCHAR(64) COMMENT '区县';
ALTER TABLE t_tenant ADD COLUMN industry VARCHAR(64) COMMENT '所属行业';
ALTER TABLE t_tenant ADD COLUMN legal_person VARCHAR(64) COMMENT '法人代表';
ALTER TABLE t_tenant ADD COLUMN province VARCHAR(64) COMMENT '省份';
ALTER TABLE t_tenant ADD COLUMN remark VARCHAR(500) COMMENT '备注';
ALTER TABLE t_tenant ADD COLUMN source VARCHAR(32) DEFAULT 'MANUAL' COMMENT '来源（MANUAL/SELF_REGISTER/INVITATION）';
ALTER TABLE t_tenant ADD COLUMN suspend_reason VARCHAR(255) COMMENT '停用原因';
ALTER TABLE t_tenant ADD COLUMN suspended_at DATETIME COMMENT '停用时间';